---
- name: 0x1337 Networking Services Concourse/Ansible Pipeline
  hosts: all
  connection: local
  gather_facts: False

  tasks:
  - name: Test ssh Connection
    shell: echo $HOSTNAME
    register: result

  - debug:
    var: result
