---
- name: 0x1337 Networking Services Concourse/Ansible Pipeline
  hosts: all
  gather_facts: false

  tasks:
  - name: "test 250"
    local_action: command ping -c 2 192.168.80.250

  - name: "test 5"
    local_action: command ping -c 2 192.168.80.5

  - name: "test"
    local_action: command ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null 192.168.80.5

  - name: Test ssh Connection
    shell: echo $HOSTNAME
    register: result

  - debug:
      var: result
