---
- name: 0x1337 Networking Services Concourse/Ansible Pipeline
  hosts: all
  gather_facts: false

  tasks:
  - name: ping
    action: ping
    register: debug
  
  - debug:
      var: debug

  - debug:
      var: ansible_facts
