---
- name: 0x1337 Networking Services Concourse/Ansible Pipeline
  hosts: all
  gather_facts: false

  tasks:
  - name: Load config variables and vault secret
    include_vars:
      dir: vars
      ignore_unknown_extensions: True
      extensions: ['yml']
    no_log: 'yes'

  - name: Copy SSH private key
    copy:
      content: "{{ vault_ssh_key }}"
      dest: "/opt/resource/id_rsa"
      mode: 0600
    run_once: true
    delegate_to: 127.0.0.1

  - block:
      - debug: msg="Hello"
      - fail: msg="Initial failure"
    rescue:
      - debug: msg="Rescued"
    always:
      - fail: msg="Failed"

  - name: 
    block:
      - name: login and print hostname using raw command
        raw: cat /etc/hostname
        register: raw_command
      - name:
        ping:
    ignore_errors: 'yes'
  
  - debug:
      var: raw_command
