---
- name: 0x1337 Networking Services Concourse/Ansible Pipeline
  hosts: all
  gather_facts: false

  tasks:
  - name: Load config variables and vault secret
    include_vars:
      dir: vars
      ignore_unknown_extensions: True
      extensions: ['yml']

  - name: Hostname
    raw: cat /etc/hostname
    ignore_errors: yes

  - ping:
      data: var_ping
    ignore_errors: yes
  
  - debug:
      var: var_ping
