---
- name: 0x1337 Networking Services Concourse/Ansible Pipeline
  hosts: all

  tasks:
  - debug:
      var: ansible_facts
  
  - name: "ping test"
    ping:
      data: crash

  - debug:
      var: crash

  - name: Test ssh Connection
    shell: echo $HOSTNAME
    register: result

  - debug:
      var: result
