---
- name: 0x1337 Networking Services Concourse/Ansible Pipeline
  hosts: all
  gather_facts: true

  tasks:
  - debug: var=ansible_facts
  - debug:
      var: ansible_env
  
  - name: "ping test"
    ping:
      data: crash

  - debug:
      var: crash

  - name: Test ssh Connection
    shell: echo $HOSTNAME
    register: result

  - debug:
      var: result
