---
- name: 0x1337 Networking Services Concourse/Ansible Pipeline
  hosts: all
  gather_facts: false

  tasks:
  - name: Load config variables and vault secret
    include_vars:
      dir: vars
      ignore_unknown_extensions: True
      extensions: ['yml']
    no_log: 'yes'

  - name: Copy SSH private key
    copy:
      content: "{{ vault_ssh_key }}"
      dest: "~/.ssh/id_rsa"
      mode: 0600
    run_once: true
    delegate_to: 127.0.0.1

  - name: list .ssh dir
    raw: ls ~/.ssh/* -al
    delegate_to: 127.0.0.1

  - name: Hostname
    raw: cat /etc/hostname
    ignore_errors: 'yes'

  - ping:
      data: var_ping
    ignore_errors: yes
  
  - debug:
      var: var_ping
