---
- name: 0x1337 Networking Services Concourse/Ansible Pipeline
  hosts: all
  gather_facts: false

  tasks:
  - name: Load config variables and vault secret
    include_vars:
      dir: vars
      ignore_unknown_extensions: True
      extensions: ['yml']

  - name: ping
    action: ping
    register: var_ping
    ignore_errors: yes
  
  - debug:
      var: var_ping

  - name: Display variable from encrypted vault
    debug:
      var: vault_ssh_key
