---
- name: 0x1337 Networking Services Concourse/Ansible Pipeline
  hosts: all
  gather_facts: false

  tasks:
  - name: Load config variables and vault secret
    include_vars:
      dir: vars
      ignore_unknown_extensions: True
      extensions: ['yml']
    no_log: 'yes'

  - name: Copy SSH private key
    copy:
      content: "{{ vault_ssh_key }}"
      dest: "/opt/resource/id_rsa"
      mode: 0600
    changed_when: false
    run_once: true
    delegate_to: 127.0.0.1

  - name: Create new user if not exists
    vars:
      - ansible_user: "{{ initial_user | default('root') }}"
      - username: "{{ initial_user | default('rgr') }}"

    block:
      - name: Check if new user already exists
        command: 'ssh -q -o BatchMode=yes -o ConnectTimeout=3 {{ username }}@{{ inventory_hostname }} "echo OK"'
        delegate_to: localhost
        changed_when: false
        failed_when: false
        register: check_new_user

      - name: Create new user
        import_role:
          name: template
        when: not "OK" in check_new_user.stdout

      - debug:
          var: check_new_user

  # - name: Set facts
  #   set_fact:
  #     ansible_ssh_pass: "{{ vault_ssh_password }}"
  
  # - block:
  #     - debug: msg="Hello"
  #     - raw: cat /etc/hostname
  #       register: raw_command
  #   rescue:
  #     - debug: msg="Rescued"

  # - debug:
  #     var: raw_command
