---
- name: 0x1337 Networking Services Concourse/Ansible Pipeline
  hosts: all
  gather_facts: false

  tasks:
  - name: "ping test"
    ping: "192.168.80.5"

  - name: Test ssh Connection
    shell: echo $HOSTNAME
    register: result

  - debug:
      var: result
