---
- name: 0x1337 Networking Services Concourse/Ansible Pipeline
  hosts: all
  gather_facts: false

  tasks:
  - name: "test 250"
    net_ping:
      dest: 192.168.80.250
    delegate_to: 127.0.0.1

  - name: "test 5"
    local_action: command ping -c 2 192.168.80.5

  - name: "ping test"
    ping:

  - name: Test ssh Connection
    shell: echo $HOSTNAME
    register: result

  - debug:
      var: result
