---
# ./roles/template/tasks/main.yml

- raw: apt-get -y install python3
  register: raw_command

- debug:
    var: raw_command

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - python
    - sudo
