---
# ./roles/template/tasks/main.yml

- raw: apt -y install python3 python3-apt
  register: raw_command

- debug:
    var: raw_command

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: present
  become: true
  loop:
    - sudo

- name: Copy a new "sudoers" file into place
  copy:
    src: ./sudoers
    dest: /etc/sudoers

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
